name: GitHub Pages - Angular 20.3.0

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.11.1'

      - name: Install dependencies
        run: npm install

      - name: Inject environment variables into Angular
        env: # Step-level environment variables
          PASSWORD_HASH: ${{ secrets.PASSWORD_HASH }} # Ensure this secret is set in your repository settings
        run: |
          # Example: Inject environment variables into Angular's environment.ts
          sed -i "s|PASSWORD_HASH_PLACEHOLDER|${{ env.PASSWORD_HASH }}|g" src/environments/environment.ts

      - name: Extract repository name from package.json
        id: package
        run: echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT

      - name: Build Angular app for GitHub Pages
        run: npm run build:gh --configuration=production

      - name: Copy error files to redirect to home
        run: npm run copy-error-page

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base_href: /${{ steps.package.outputs.name }}/ # make sure this corresponds to https://<your_username>.github.io/<base_href>/
          deploy_branch: gh-pages
          publish_dir: dist/${{ steps.package.outputs.name }}/browser
          enable_jekyll: true
